/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Nov 10 2016
 * Processor: PIC16F873A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }